name: Tests for software/gps

on:
  push:
    branches: [ $default-branch ]
    paths: [ software/gps/** ]
  pull_request:
    branches: [ $default-branch ]
    paths: [ software/gps/** ]
  workflow_dispatch:
    branches: [ $default-branch ]
    paths: [ software/gps/** ]

jobs:
  build:
    defaults:
      run:
        working-directory: software/gps

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('software/gps/poetry.lock') }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install --no-root

    - name: Run checks
      run: ./check.sh