name: Tests for v1/software/co2

on:
  push:
    branches: [ $default-branch ]
    paths: [ v1/software/co2/** ]
  pull_request:
    branches: [ $default-branch ]
    paths: [ v1/software/co2/** ]
  workflow_dispatch:
    branches: [ $default-branch ]
    paths: [ v1/software/co2/** ]

jobs:
  build:
    defaults:
      run:
        working-directory: v1/software/co2

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('software/co2/poetry.lock') }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install --no-root

    - name: Run checks
      run: ./check.sh